version: '3'
services:
  emailserver:
    build: ./eMailServer
    # container_name: "haraka_tracking_prevention"
    restart: unless-stopped
    ports:
      - "25:25"

  loadbalancer:
    image: dockercloud/haproxy
    restart: unless-stopped
    links:
      - detectionengine
    expose:
      - "8080"

  detectionengine:
    build: ./detectionEngine
    restart: unless-stopped
    expose:
      - "8080"